version: '3'
services:
    gpt-pilot:
        environment:
            - OPENAI_ENDPOINT=http://10.1.1.1:11434/v1/chat/completions
            - OPENAI_API_KEY=ollama
            - MODEL_NAME=codellama:7b-instruct-fp16
            - MAX_TOKENS=8192
            - DATABASE_TYPE=postgres
            - DB_NAME=pilot
            - DB_HOST=postgres
            - DB_PORT=5431
            - DB_USER=pilot
            - DB_PASSWORD=pilot
        volumes:
            - /DATA/Downloads/pythagora/gpt-pilot/workspace:/usr/src/app/workspace
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "0.0.0.0:7681:7681"
            - "0.0.0.0:3000:3000"
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: pilot
            POSTGRES_PASSWORD: pilot
            POSTGRES_DB: pilot
        ports:
        - "0.0.0.0:5431:5431"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U pilot"]
            interval: 30s
            timeout: 10s
            retries: 3
